### ISSUE TITLE
Mehr Kuhbilder, Mirco

### ISSUE THREAD

**Issue by carolineheitz** [carolineheitz/Test_Repo#2]

**Comment by mircobrunner** [comment]
![trapped_trees_2](https://user-images.githubusercontent.com/45977193/50289421-16140a00-0469-11e9-9385-d6e2cacff69d.png)

**Comment by mircobrunner** [comment]
![trapped_trees](https://user-images.githubusercontent.com/45977193/50289450-2a580700-0469-11e9-8def-968605201b14.png)

**Comment by mircobrunner** [comment]
![trapped_trees_3](https://user-images.githubusercontent.com/45977193/50289464-304de800-0469-11e9-86e8-9a9b9b592825.png)
